### ISSUE TITLE
 Implementar GET /tweets y GET/users

### ISSUE THREAD

**Issue by sambrista** [rafaelbv95/tweetfony#4]

**Comment by rafaelbv95** [comment]
Hecho

**Comment by sambrista** [comment]
Comprobado.

Yo en principio pedía una lista de tweets y de usuarios. Tu devuelves un objeto con el total y la lista, que contiene los enlaces pero también el nombre. ¿Está mal? No, también está bien.

Las APIs REST proporcionan una serie de reglas a seguir, pero definir exactamente cuál va a ser la respuesta es algo que depende del diseñador de la API. Es por esto que es fundamental que una API esté bien documentada.
